# Generated by Django 4.1 on 2022-08-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.TextField(blank=True),
        ),
    ]
